title: "Sarvesh R"
description: >- 
  Final year Biomedical Engineering student passionate about technology, software, and cybersecurity.
url: "https://iamsarveshr.github.io"
baseurl: ""
repository: "iamsarveshr/iamsarveshr.github.io"

# Author Info
author:
  name: "Sarvesh R"
  avatar: "/assets/images/avatar.jpg"  # Add your photo here later
  bio: "From BME to Tech. Intern @ Securden. Curious, Consistent, Evolving."
  location: "India"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/iamsarveshr"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "#"  # Add your link
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "#"  # Your Infohood24 or professional page
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your.email@example.com"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"  # Clean blue theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
